### ISSUE TITLE
settings.local

### ISSUE THREAD

**Issue by mdotasia** [Freyert/LeakyGenerator#1]
You mention in https://github.com/yeoman/generator/issues/778 that calling sub-generator works after setting settings.local in composeWith invocation. What do you put as settings.local?

**Comment by mdotasia** [comment]
Further to my comment above, when running `mocha` on this project, I get the error below, which seems different from the leak you mentioned. So just wondering how to invoke a sub-generator since the syntax seems to have changed.
```
1) leaky:app "before all" hook:
     Uncaught Error: You don't seem to have a generator with the name leaky:leaky installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 1 registered generators run yo with the `--help` option.
      at Environment.create (node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:265:7)
      at composeWith (node_modules/yeoman-generator/lib/base.js:586:26)
      at module.exports.yeoman.generators.Base.extend.writing.leak (app/index.js:35:12)
      at node_modules/yeoman-generator/lib/base.js:409:16
```

**Comment by mdotasia** [comment]
See https://github.com/yeoman/yeoman.github.io/issues/550.
